### ISSUE TITLE
Support .tsx extension

### ISSUE THREAD

**Issue by benmerckx** [testpossessed/auto-barrel#2]
I notice auto-barrel doesn't seem to support files with .tsx extension and couldn't find a related setting to change that?

**Comment by testpossessed** [comment]
Hi Ben,

Thanks for taking the time to evaluate the extension.

Indeed it doesn't support JSX or TSX extensions.  I never thought of these because I don't use the extensions in React work.  I tend to just stick to JS and TS as I have seen many others do.

Shouldn't be hard to implement.  I would suggest though that the barrel files remain either .js or .ts and that the settings remain the same.  I would just add support for recognising .jsx/.tsx files (existing or added later) and including them in the barrel file.

I have been thinking for some time that I should make the language a pick list including JavaScript and TypeScript rather than expecting users to set the extension.  I will make that change as part of this to make it clearer that you are choosing the language not the extension.

**Comment by testpossessed** [comment]
I just published an update to the VS Marketplace that supports including both .jsx and .tsx files in barrels.  Barrel files still use .js or .ts though.

**Comment by benmerckx** [comment]
There's no need for a jsx or tsx extension on the index file as it won't contain jsx anyway. Can confirm it works. That was quick, thanks a lot!
